# NumPy

NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.

Travis Oliphant created NumPy package in 2005 by injecting the features of the ancestor module Numeric into another module Numarray.

It is an extension module of Python which is mostly written in C. It provides various functions which are capable of performing the numeric computations with a high speed.

NumPy provides various powerful data structures, implementing multi-dimensional arrays and matrices. These data structures are used for the optimal computations regarding arrays and matrices.

## Need of NumPy

With the revolution of data science, data analysis libraries like NumPy, SciPy, Pandas, etc. have seen a lot of growth. With a much easier syntax than other programming languages, python is the first choice language for the data scientist.

NumPy provides a convenient and efficient way to handle the vast amount of data. NumPy is also very convenient with Matrix multiplication and data reshaping. NumPy is fast which makes it reasonable to work with a large set of data.

There are the following advantages of using NumPy for data analysis.

- NumPy performs array-oriented computing.
- It efficiently implements the multidimensional arrays.
- It performs scientific computations.
- It is capable of performing Fourier Transform and reshaping the data stored in multidimensional arrays.
- NumPy provides the in-built functions for linear algebra and random number generation

## Arrays in NumPy

- Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
- Number of dimensions of the array is called rank of the array.
- A tuple of integers giving the size of the array along each dimension is known as shape of the array.
- An array class in Numpy is called as ndarray.
- Ndarray is the n-dimensional array object defined in the numpy which stores the collection of the similar type of elements. 
- Each element of the Array object contains the same size in the memory.
- Each element in ndarray is an object of data-type object (called dtype).

## Creating a NumPy Array

Arrays in Numpy can be created by multiple ways, with various number of Ranks, defining the size of the Array. Arrays can also be created with the use of various data types such as lists, tuples, etc. The type of the resultant array is deduced from the type of the elements in the sequences

## Ways of creating an array

### Using array() method

#### Other 3 ways of creating an array
 1. Array From Numerical Ranges
   - arange()
   - linspace()
   - logspace()
 2. Array From existing data
   - asarray()
   - frombuffer()
   - fromiter()
 3. Array Creation Routines 
   - empty()
   - zeros()
   - ones()
   - eye()
   - full()

### Data Types ( dtype )
- bool_
- int_
- intc
- intp
- int 8 (i1)
- int16 (i2)
- int32 (i3)
- int64 (i4)
- uint8
- uint16
- uint32
- uint64
- float_
- float16
- float32
- float64
- complex_
- complex64
- complex128

### Character Code of dtype
- 'b' − boolean
- 'i' − (signed) integer
- 'u' − unsigned integer
- 'f' − floating-point
- 'c' − complex-floating point
- 'm' − timedelta
- 'M' − datetime
- 'O' − (Python) objects
- 'S', 'a' − (byte-)string
- 'U' − Unicode
- 'V' − raw data (void)

In [1]:
import numpy as np

In [ ]:
np.

In [3]:
A1 = np.array([1,2,3])
A1

array([1, 2, 3])

In [4]:
A2 = np.array((1,2,3),dtype='f')
A2

array([1., 2., 3.], dtype=float32)

In [5]:
A3 = np.array([ [1,2,3],[1,2,3] ],dtype='complex')
A3

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [1.+0.j, 2.+0.j, 3.+0.j]])

In [6]:
A4 = np.array( [ [1,2,3],[1,2] ] ) #important
A4

array([list([1, 2, 3]), list([1, 2])], dtype=object)

In [7]:
A5 = np.array( [ [1,2,3],[4,5,6] ] )
A5

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# three - dimensional matrix
A6 =np.array( [ [ [4,5] , [2,3] ] , [ [7,8] , [1,0]] ] )
A6

array([[[4, 5],
        [2, 3]],

       [[7, 8],
        [1, 0]]])

## Array from numerical ranges

In [9]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b = np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [11]:
c = np.arange(1,10,dtype='f')
c

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [12]:
d = np.linspace(1,2,2)
d

array([1., 2.])

In [13]:
e = np.linspace(1,2,10,dtype='i')
e

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 2], dtype=int32)

In [14]:
f = np.linspace(-1,1,3,dtype='f')
f

array([-1.,  0.,  1.], dtype=float32)

In [15]:
g = np.linspace(0,1)
g

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [16]:
i = np.linspace(1,6,5)
i

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [17]:
j = np.linspace(1,6,5,endpoint=False)
j

array([1., 2., 3., 4., 5.])

In [18]:
k = np.logspace(0,1,2)
k

array([ 1., 10.])

In [19]:
k2 = np.logspace(0,1,2,base=2)
k2

array([1., 2.])

In [20]:
m = np.logspace(1,50)
m

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10, 1.e+11, 1.e+12, 1.e+13, 1.e+14, 1.e+15, 1.e+16,
       1.e+17, 1.e+18, 1.e+19, 1.e+20, 1.e+21, 1.e+22, 1.e+23, 1.e+24,
       1.e+25, 1.e+26, 1.e+27, 1.e+28, 1.e+29, 1.e+30, 1.e+31, 1.e+32,
       1.e+33, 1.e+34, 1.e+35, 1.e+36, 1.e+37, 1.e+38, 1.e+39, 1.e+40,
       1.e+41, 1.e+42, 1.e+43, 1.e+44, 1.e+45, 1.e+46, 1.e+47, 1.e+48,
       1.e+49, 1.e+50])

## Array From Existing Data

In [21]:
r1 = [1,2,3,4]
r2 = np.asarray(r1)
print(r2)
print(type(r2))

[1 2 3 4]
<class 'numpy.ndarray'>


In [22]:
r3 = (1,2,3,4)
r4 = np.asarray(r3,dtype='f')
print(r4)
print(type(r4))

[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [23]:
s1 = [ [1,2,3],[4,5,6],[7,8,9] ]
print(np.asarray(s1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
s2 = [ [1,2,3],[4,5,6],[7,8,9] ]
print(np.asarray(s2,dtype='f'))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [25]:
t = b'hello world'  
print(type(t))  
u = np.frombuffer(t, dtype = "S1")  
print(u)  
print(type(u))  

<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
<class 'numpy.ndarray'>


In [26]:
v = [1,2,3,4,5]
it = iter(v)
print(np.fromiter(it,dtype='f'))

[1. 2. 3. 4. 5.]


In [27]:
w = [1,2,3,4,5]
ite = iter(w)
print(np.fromiter(ite,dtype='f',count=3))

[1. 2. 3.]


## Array from Creation Routines

In [28]:
x = np.empty((3,2),dtype='i')
x

array([[          0, -1074790400],
       [          0,           0],
       [          0,  1072693248]], dtype=int32)

In [29]:
y = np.zeros((2,3))
y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
z = np.ones((2,2))
z

array([[1., 1.],
       [1., 1.]])

In [31]:
N = np.eye(3)
N

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
n = np.eye(3,3)
n

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
n = np.eye(3,2)
n

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [34]:
o = np.eye(3,3,k=1)
o

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [35]:
p = np.eye(3,k=-1,dtype='i')
p

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]], dtype=int32)

In [36]:
f1 = np.full((2,3),34)
f1

array([[34, 34, 34],
       [34, 34, 34]])

## Multi-dimensional arrays can be cretaed using

- array()
- asarray()
- empty()
- zeros()
- ones()
- full()

In [37]:
q = np.array( [  [4,5,1] , [6,2,3] , [7,8,9] ] )
q

array([[4, 5, 1],
       [6, 2, 3],
       [7, 8, 9]])

In [38]:
np.diag(q)

array([4, 2, 9])

In [39]:
np.diag(q,k=1)

array([5, 3])

In [40]:
np.diag(q,k=2)

array([1])

In [41]:
np.diag(q,k=-1)

array([6, 8])

In [42]:
np.diag(q,k=-2)

array([7])

# Array Attributes

- shape
- reshape()
- ndim
- itemsize
- size
- dtype
- data

In [43]:
k1 = np.array([ [1,2,3],[4,5,6] ])

In [44]:
k1

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
k1.shape

(2, 3)

In [46]:
k1.shape = (3,2)
k1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
k1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
k1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
k1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
k2 = np.arange(12)
k2 = k2.reshape(2,2,3) #(row,colum,totalelements)
k2 

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [51]:
k1.ndim

2

In [52]:
k2.ndim

3

In [53]:
k3 = np.array([1,2,3,4],dtype='i1')
k3

array([1, 2, 3, 4], dtype=int8)

In [54]:
k3.itemsize

1

In [55]:
k4 = np.array([1,2,3,4],dtype='i2')
k4

array([1, 2, 3, 4], dtype=int16)

In [56]:
k4.itemsize

2

In [57]:
k1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
k1.size

6

In [59]:
k2

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [60]:
k2.size

12

In [61]:
k3

array([1, 2, 3, 4], dtype=int8)

In [62]:
k3.dtype

dtype('int8')

In [63]:
k4

array([1, 2, 3, 4], dtype=int16)

In [64]:
k4.dtype

dtype('int16')

In [65]:
k3

array([1, 2, 3, 4], dtype=int8)

In [66]:
k3.data

# Mathematical Operations

- Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [67]:
x = np.array([ [4,7,3],[3,1,0] ])
x

array([[4, 7, 3],
       [3, 1, 0]])

In [68]:
y = np.array([ [3,5,1],[0,1,3] ])
y

array([[3, 5, 1],
       [0, 1, 3]])

In [69]:
x + y 

array([[ 7, 12,  4],
       [ 3,  2,  3]])

In [70]:
np.add(x,y)

array([[ 7, 12,  4],
       [ 3,  2,  3]])

In [71]:
x - y

array([[ 1,  2,  2],
       [ 3,  0, -3]])

In [72]:
np.subtract(x,y)

array([[ 1,  2,  2],
       [ 3,  0, -3]])

In [73]:
x // y

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([[1, 1, 3],
       [0, 1, 0]], dtype=int32)

In [74]:
np.divide(x,y)

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[1.33333333, 1.4       , 3.        ],
       [       inf, 1.        , 0.        ]])

In [75]:
x**2

array([[16, 49,  9],
       [ 9,  1,  0]], dtype=int32)

In [76]:
np.power(x,2)

array([[16, 49,  9],
       [ 9,  1,  0]], dtype=int32)

In [77]:
y**3

array([[ 27, 125,   1],
       [  0,   1,  27]], dtype=int32)

In [78]:
np.power(y,3)

array([[ 27, 125,   1],
       [  0,   1,  27]], dtype=int32)

#### Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [79]:
# elements multiplication
x*y

array([[12, 35,  3],
       [ 0,  1,  0]])

In [80]:
np.multiply(x,y)

array([[12, 35,  3],
       [ 0,  1,  0]])

In [81]:
a = np.arange(11,20)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [82]:
b = np.arange(9)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
a = a.reshape(3,3)
a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [84]:
b = b.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
a @ b

array([[114, 150, 186],
       [141, 186, 231],
       [168, 222, 276]])

In [86]:
a.dot(b)

array([[114, 150, 186],
       [141, 186, 231],
       [168, 222, 276]])

- Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [87]:
a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [88]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [89]:
c = a+b
c

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [90]:
a+=b
a

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [91]:
a

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

# Universal Functions

In [92]:
a

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [93]:
a.min()

11

In [94]:
a.max()

27

In [95]:
abs(a)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [96]:
a.all()

True

In [97]:
sum(a)

array([51, 57, 63])

In [98]:
a.any()

True

In [99]:
len(a)

3

## axis

- axis=0 is for column
- axis=1 is for row

In [100]:
a

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [101]:
a.sum(axis=0)

array([51, 57, 63])

In [102]:
a.sum(axis=1)

array([39, 57, 75])

In [103]:
a.min(axis=0)

array([11, 13, 15])

In [104]:
a.min(axis=1)

array([11, 17, 23])

In [105]:
a.cumsum(axis=0) # cumulative sum along each column

array([[11, 13, 15],
       [28, 32, 36],
       [51, 57, 63]], dtype=int32)

In [106]:
a.cumsum(axis=1) # cumulative sum along each row

array([[11, 24, 39],
       [17, 36, 57],
       [23, 48, 75]], dtype=int32)

## Trigonometric Functions

In [107]:
z = np.array([0,30,45,60,90])
z

array([ 0, 30, 45, 60, 90])

In [108]:
np.sin(z)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [109]:
np.cos(z)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

# Statistical Functions

In [110]:
a

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [111]:
a.mean()

19.0

In [112]:
a.mean(axis=0)

array([17., 19., 21.])

In [113]:
a.mean(axis=1)

array([13., 19., 25.])

In [114]:
np.median(a)

19.0

In [115]:
np.median(a,axis=0)

array([17., 19., 21.])

In [116]:
np.median(a,axis=1)

array([13., 19., 25.])

In [117]:
np.average(a)

19.0

In [118]:
np.average(a,axis=0)

array([17., 19., 21.])

In [119]:
np.average(a,axis=1)

array([13., 19., 25.])

In [120]:
np.std(a)

5.163977794943222

In [121]:
np.std(a,axis=0)

array([4.89897949, 4.89897949, 4.89897949])

In [122]:
np.std(a,axis=1)

array([1.63299316, 1.63299316, 1.63299316])

In [123]:
np.var(a)

26.666666666666668

In [124]:
np.var(a,axis=0)

array([24., 24., 24.])

In [125]:
np.var(a,axis=1)

array([2.66666667, 2.66666667, 2.66666667])

#### percentile()
- Percentile (or a centile) is a measure used in statistics indicating the value below which a given percentage of observations in a group of observations fall. The function numpy.percentile() takes the following arguments.

np.percentile(a, q, axis)

a = input array
q = The percentile to compute must be between 0-100
axis= The axis along which the percentile is to be calculated

In [126]:
np.percentile(a,20)

14.200000000000001

In [127]:
np.percentile(a,40,axis=0)

array([15.8, 17.8, 19.8])

In [128]:
np.percentile(a,80,axis=1)

array([14.2, 20.2, 26.2])

# Indexing and Slicing

#### Three types of indexing methods are available 
- field access
- basic slicing
- advanced indexing.

- One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [129]:
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
ar[0]

0

In [131]:
ar[0:10:3]

array([0, 3, 6, 9])

In [132]:
s = slice(0,10,3)
ar[s]

array([0, 3, 6, 9])

- Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas

In [133]:
l = [ [3,4,2],[5,3,9],[6,1,7],[8,2,5] ]
ar2 = np.asarray(l)
ar2

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7],
       [8, 2, 5]])

In [134]:
ar2[0]

array([3, 4, 2])

In [135]:
ar2[0][1]

4

In [136]:
ar2[0:3]

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7]])

In [137]:
ar2[0:3:2]

array([[3, 4, 2],
       [6, 1, 7]])

- Slicing can also include ellipsis (…) to make a selection tuple of the same length as the dimension of an array. If ellipsis is used at the row position, it will return an ndarray comprising of items in rows.
- The dots (...) represent as many colons as needed to produce a complete indexing tuple. 

In [138]:
ar2[...]

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7],
       [8, 2, 5]])

In [139]:
ar2[1,...] # rows

array([5, 3, 9])

In [140]:
ar2[...,2] # columns

array([2, 9, 7, 5])

In [141]:
ar2[2:,...]

array([[6, 1, 7],
       [8, 2, 5]])

In [142]:
ar2[...,1:]

array([[4, 2],
       [3, 9],
       [1, 7],
       [2, 5]])

# Advanced Indexing

- Advanced indexing always returns a copy of the data. As against this, the slicing only presents a view.

- There are two types of advanced indexing 
  1. Integer 
  2. Boolean.

In [143]:
ar2

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7],
       [8, 2, 5]])

### 1. Integer Array Indexing
This mechanism helps in selecting any arbitrary item in an array based on its Ndimensional index. Each integer array represents the number of indexes into that dimension. When the index consists of as many integer arrays as the dimensions of the target ndarray, it becomes straightforward.

In the following example, one element of specified column from each row of ndarray object is selected. Hence, the row index contains all row numbers, and the column index specifies the element to be selected.

In [144]:
ar2[[0,1,2,3],[1,2,0,1]] # (0,1) (1,2) (2,0) (3,1)

array([4, 9, 6, 2])

In [145]:
ar2[ [0,1,2],[0,1,2] ] #diagonal elements (0,0) (1,1) (2,2)

array([3, 3, 7])

In [146]:
ar2[1:4,1:3]

array([[3, 9],
       [1, 7],
       [2, 5]])

In [147]:
ar2[1:4,[1,2]]

array([[3, 9],
       [1, 7],
       [2, 5]])

### 2. Boolean Array Indexing

- This type of advanced indexing is used when the resultant object is meant to be the result of Boolean operations, such as comparison operators.

In [148]:
ar2

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7],
       [8, 2, 5]])

In [149]:
ar2[ar2 > 5]

array([9, 6, 7, 8])

In [150]:
ar2[ar2 % 2 == 0]

array([4, 2, 6, 8, 2])

####  NaN (Not a Number) elements are omitted by using ~ (complement operator).

In [151]:
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

#### filter out the non-complex elements from an array.

In [152]:
a = np.array([1, 2+6j, 5, 3.5+5j]) 
a[~np.iscomplex(a)]

array([1.+0.j, 5.+0.j])

# Broadcasting

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes.

#### Broadcasting is possible if the following rules are satisfied −

- Array with smaller ndim than the other is prepended with '1' in its shape.
- Size in each dimension of the output shape is maximum of the input sizes in that dimension.
- An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.
- If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimension.

A set of arrays is said to be broadcastable if the above rules produce a valid result and one of the following is true −

- Arrays have exactly the same shape.
- Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.
- Array having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated property is true.

In [153]:
a = np.array([ [1, 2, 3], [4, 5, 6],[7, 8, 9] ])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
b = np.array([4,7,2])
b

array([4, 7, 2])

In [155]:
a+b

array([[ 5,  9,  5],
       [ 8, 12,  8],
       [11, 15, 11]])

# Iterating over Array

### Iterating over multidimensional arrays is done with respect to the first axis:

In [156]:
ar2

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7],
       [8, 2, 5]])

In [157]:
for i in ar2:
    print(i)

[3 4 2]
[5 3 9]
[6 1 7]
[8 2 5]


- if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:

In [158]:
for i in ar2.flat:
    print(i)

3
4
2
5
3
9
6
1
7
8
2
5


### NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

In [159]:
ar2

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7],
       [8, 2, 5]])

In [160]:
for i in ar2:
    print(i)

[3 4 2]
[5 3 9]
[6 1 7]
[8 2 5]


In [161]:
for i in np.nditer(ar2):
    print(i)

3
4
2
5
3
9
6
1
7
8
2
5


# Array Manipulation

Several routines are available in NumPy package for manipulation of elements in ndarray object. They can be classified into the following types −

1. Changing Shape
    - reshape
    - flat
    - flatten
    - ravel
2. Transpose Operations
    - transpose
    - ndarray.T
    - rollaxis
    - swapaxes
3. Changing Dimensions
    - broadcast
    - broadcast_to
    - expand_dims
    - squeze
4. Joining Arrays
    - concatenate
    - stack
    - hstack
    - vstack
5. Splitting Arrays
    - split
    - hsplit
    - vsplit
6. Adding / Removing Elements
    - resize
    - append
    - insert
    - delete
    - unique

In [162]:
ar2

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7],
       [8, 2, 5]])

In [163]:
ar2.reshape(3,4)

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [164]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
ar.flat[0]

0

In [166]:
ar.flat[1]

1

In [167]:
ar2

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7],
       [8, 2, 5]])

In [168]:
ar2.flatten()

array([3, 4, 2, 5, 3, 9, 6, 1, 7, 8, 2, 5])

In [169]:
ar2.ravel()

array([3, 4, 2, 5, 3, 9, 6, 1, 7, 8, 2, 5])

In [170]:
ar2.transpose()

array([[3, 5, 6, 8],
       [4, 3, 1, 2],
       [2, 9, 7, 5]])

In [171]:
ar2.T

array([[3, 5, 6, 8],
       [4, 3, 1, 2],
       [2, 9, 7, 5]])

In [172]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [173]:
np.stack((x,y)) # axis=0

array([[1, 2, 3],
       [4, 5, 6]])

In [174]:
np.stack((x,y),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [175]:
np.hstack((x,y))

array([1, 2, 3, 4, 5, 6])

In [176]:
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

In [177]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
np.split(ar,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [179]:
np.split(ar,[1,3,5])

[array([0]), array([1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]

In [180]:
ar2

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7],
       [8, 2, 5]])

In [181]:
np.hsplit(ar2,1)

[array([[3, 4, 2],
        [5, 3, 9],
        [6, 1, 7],
        [8, 2, 5]])]

In [182]:
np.hsplit(ar2,3)

[array([[3],
        [5],
        [6],
        [8]]), array([[4],
        [3],
        [1],
        [2]]), array([[2],
        [9],
        [7],
        [5]])]

In [183]:
np.vsplit(ar2,1)

[array([[3, 4, 2],
        [5, 3, 9],
        [6, 1, 7],
        [8, 2, 5]])]

In [184]:
np.vsplit(ar2,2)

[array([[3, 4, 2],
        [5, 3, 9]]), array([[6, 1, 7],
        [8, 2, 5]])]

In [185]:
np.vsplit(ar2,4)

[array([[3, 4, 2]]),
 array([[5, 3, 9]]),
 array([[6, 1, 7]]),
 array([[8, 2, 5]])]

In [186]:
ar2.shape

(4, 3)

In [187]:
ar2.resize(3,4)

In [188]:
ar2.shape

(3, 4)

In [189]:
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [190]:
np.append(ar2,[0,0,0])

array([3, 4, 2, 5, 3, 9, 6, 1, 7, 8, 2, 5, 0, 0, 0])

In [191]:
np.append(ar2,[[0,0,0,0]],axis=0)

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5],
       [0, 0, 0, 0]])

In [192]:
np.append(ar2,[ [0],[0],[0] ], axis=1)

array([[3, 4, 2, 5, 0],
       [3, 9, 6, 1, 0],
       [7, 8, 2, 5, 0]])

In [193]:
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [194]:
np.insert(ar2,3,[0,0,0])

array([3, 4, 2, 0, 0, 0, 5, 3, 9, 6, 1, 7, 8, 2, 5])

In [195]:
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [196]:
np.insert(ar2,1,[1,2,3,4],axis=0)

array([[3, 4, 2, 5],
       [1, 2, 3, 4],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [197]:
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [198]:
np.insert(ar2,1,[0],axis=0) # broadcast

array([[3, 4, 2, 5],
       [0, 0, 0, 0],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [199]:
np.insert(ar2,2,[9,9,9],axis=1)

array([[3, 4, 9, 2, 5],
       [3, 9, 9, 6, 1],
       [7, 8, 9, 2, 5]])

In [200]:
np.insert(ar2,2,[0],axis=1)

array([[3, 4, 0, 2, 5],
       [3, 9, 0, 6, 1],
       [7, 8, 0, 2, 5]])

In [201]:
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [202]:
np.unique(ar2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
np.unique(ar2,return_index=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([7, 2, 0, 1, 3, 6, 8, 9, 5], dtype=int64))

In [204]:
np.unique(ar2,return_inverse=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([2, 3, 1, 4, 2, 8, 5, 0, 6, 7, 1, 4], dtype=int64))

In [205]:
np.unique(ar2,return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 2, 2, 1, 2, 1, 1, 1, 1], dtype=int64))

In [206]:
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [207]:
np.delete(ar2,9) # value at index=9 i.e. 8 is deleted

array([3, 4, 2, 5, 3, 9, 6, 1, 7, 2, 5])

In [208]:
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [209]:
np.delete(ar2,np.s_[4:7])

array([3, 4, 2, 5, 1, 7, 8, 2, 5])

In [210]:
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [211]:
np.delete(ar2,2,axis=0)

array([[3, 4, 2, 5],
       [3, 9, 6, 1]])

In [212]:
np.delete(ar2,3,axis=1)

array([[3, 4, 2],
       [3, 9, 6],
       [7, 8, 2]])

In [213]:
np.delete(ar2,np.s_[::2],axis=1)

array([[4, 5],
       [9, 1],
       [8, 5]])

# Search, Sort and Counting Functions

In [214]:
s = np.array([3,6,2,7,9,4,8,7,0])
s

array([3, 6, 2, 7, 9, 4, 8, 7, 0])

In [215]:
np.sort(s)

array([0, 2, 3, 4, 6, 7, 7, 8, 9])

In [216]:
np.sort(s,kind='heapsort')

array([0, 2, 3, 4, 6, 7, 7, 8, 9])

In [217]:
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [218]:
np.sort(ar2)

array([[2, 3, 4, 5],
       [1, 3, 6, 9],
       [2, 5, 7, 8]])

In [219]:
np.sort(ar2,axis=0)

array([[3, 4, 2, 1],
       [3, 8, 2, 5],
       [7, 9, 6, 5]])

In [220]:
np.sort(ar2,axis=1)

array([[2, 3, 4, 5],
       [1, 3, 6, 9],
       [2, 5, 7, 8]])

In [221]:
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [222]:
np.argmax(ar2)

5

In [223]:
np.argmin(ar2)

7

In [224]:
z = np.array([0,0,0,3,0,0,2,4,0,2,8])
z

array([0, 0, 0, 3, 0, 0, 2, 4, 0, 2, 8])

In [225]:
np.nonzero(z)

(array([ 3,  6,  7,  9, 10], dtype=int64),)

In [226]:
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [227]:
np.where(ar2%2==0)

(array([0, 0, 1, 2, 2], dtype=int64), array([1, 2, 2, 1, 2], dtype=int64))

In [228]:
np.where(ar2>5)

(array([1, 1, 2, 2], dtype=int64), array([1, 2, 0, 1], dtype=int64))

In [229]:
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [230]:
condition = np.mod(ar2,2) == 0

In [231]:
np.extract(condition,ar2)

array([4, 2, 6, 8, 2])

# Copies and Views

#### While executing the functions, some of them return a copy of the input array, while some return the view. When the contents are physically stored in another location, it is called Copy. If on the other hand, a different view of the same memory content is provided, we call it as View.

In [232]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [233]:
x = ar

In [234]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [235]:
id(ar)

2380234187040

In [236]:
id(x)

2380234187040

In [237]:
ar is x

True

In [238]:
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [239]:
z = ar2.view()

In [240]:
z

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [241]:
id(ar2)

2380234225984

In [242]:
id(z)

2380233470960

In [243]:
ar2 = ar2.reshape(4,3)
ar2

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7],
       [8, 2, 5]])

In [244]:
z

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [245]:
ar2 is z

False

### Slice of an array creates a view.

# Deep Copy

The ndarray.copy() function creates a deep copy. It is a complete copy of the array and its data, and doesn’t share with the original array.

In [246]:
ar2

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7],
       [8, 2, 5]])

In [247]:
d = np.copy(ar2)

In [248]:
d

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7],
       [8, 2, 5]])

In [249]:
id(ar2)

2380234078448

In [250]:
id(d)

2380233838144

In [251]:
ar2 = ar2.reshape(3,4)
ar2

array([[3, 4, 2, 5],
       [3, 9, 6, 1],
       [7, 8, 2, 5]])

In [252]:
d

array([[3, 4, 2],
       [5, 3, 9],
       [6, 1, 7],
       [8, 2, 5]])

In [253]:
ar2 is d

False

# Matrix method in python

In [254]:
m = np.matrix([[1,2,3],[6,5,7]])
m

matrix([[1, 2, 3],
        [6, 5, 7]])

In [255]:
n = np.matrix('1,2;3,4;6,5')
n

matrix([[1, 2],
        [3, 4],
        [6, 5]])

In [256]:
m*n #matrix multiplication not elements

matrix([[25, 25],
        [63, 67]])